# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85992acfa3a9a9b1c86222fde28404973336ea545ef6e4a0659a673fecc046fd786860ddff8240737a199162a0429de43f505977a2ddaf33c88e7f34e7c955b9

test:
  secret_key_base: 2c5f8a05ceff5becb76870789ce39f9d9375d4ff6f6eb0bf3165b911b80f895f22728a35049729e7047fc4ea78bfad7016cf4781ae717d1d0f2eba2ed25bacb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
